name: API-CI

#on: [push]
on:
  push:
    paths:
      - "./**"
      - ".github/workflows/api-ci.yml"

defaults:
  run:
    working-directory: ./


jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: ./yarn.lock
      - name: Install dependencies
        shell: bash
        run: yarn install --frozen-lockfile
      - name: Run linter
        shell: bash
        run: yarn lint
