name: API CI

on:
  push:
    paths:
      - "./**"
      - ".github/workflows/api-ci.yml"
defaults:
  run:
    working-directory: ./
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'yarn'
          cache-dependency-path: ./yarn-lock.json
      - name: install
        shell: bash
        run: npm ci
      - name: run linter
        shell: bash
        run: yarn lint
